import {makeProject,makeNode,validate,clone} from '../assets/js/model.js';
import {buildTemplate} from '../assets/js/templates.js';
import {svgText,pngBlob,markdown,mermaid,html} from '../assets/js/exporters.js';
import {setLang,messages,LANGS} from '../assets/js/i18n.js';
import {TYPES,lesson} from '../assets/js/nodes.js';
const assert=(v,msg='assertion failed')=>{if(!v)throw Error(msg);};
const result=document.getElementById('results'),frame=document.getElementById('ui');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function test(name,fn){const li=document.createElement('li');li.textContent=name;result.append(li);try{await fn();li.className='pass';li.textContent='PASS — '+name;return true;}catch(e){li.className='fail';li.textContent='FAIL — '+name+' — '+e.message;return false;}}
function button(doc,name){return [...doc.querySelectorAll('button')].find(b=>b.textContent.trim()===name||b.getAttribute('aria-label')===name);}
function input(doc,label){const l=[...doc.querySelectorAll('label')].find(l=>l.querySelector('span')?.textContent===label);if(!l)throw Error('missing field '+label);return l.querySelector('input,select,textarea');}
function edit(doc,label,value){const n=input(doc,label);n.value=value;n.dispatchEvent(new Event(n.tagName==='SELECT'?'change':'input',{bubbles:true}));}
async function click(doc,name){const b=button(doc,name);if(!b)throw Error('missing button '+name);b.click();await delay(20);}
async function run(){document.getElementById('run').disabled=true;result.replaceChildren();let passed=0,total=0;const check=async(name,fn)=>{total++;if(await test(name,fn))passed++;};
 const p=buildTemplate('researchReport');
 await check('All 3 languages and 18 educational entries',()=>{for(const lang of LANGS){setLang(lang);for(const [k,v] of Object.entries(messages))assert(v.length===3&&v.every(Boolean),k);for(const type of TYPES)assert(lesson(type).length===6,type);}setLang('en');});
 await check('SVG export is valid XML, including hostile text',()=>{const q=clone(p);q.nodes[0].name='<img src=x onerror=alert(1)> & "';const source=svgText(q),xml=new DOMParser().parseFromString(source,'image/svg+xml');assert(!xml.querySelector('parsererror'));assert(!xml.querySelector('script,image,foreignObject'));assert(source.includes('&lt;img'));});
 await check('PNG export contains real raster pixels',async()=>{const blob=await pngBlob(p);assert(blob.type==='image/png');assert(blob.size>1000);const bytes=new Uint8Array(await blob.slice(0,8).arrayBuffer());assert(bytes.join(',')==='137,80,78,71,13,10,26,10');});
 await check('JSON export/import exact data round trip',()=>{assert(JSON.stringify(validate(JSON.stringify(p)))===JSON.stringify(validate(p)));});
 await check('Markdown, Mermaid and printable HTML exports',()=>{const q=clone(p);q.name='<script>alert(1)</script>';q.nodes[0].name='"] --> hacked["';assert(markdown(q).includes('```mermaid'));assert(!mermaid(q).includes('hacked["'));const doc=new DOMParser().parseFromString(html(q),'text/html');assert(!doc.querySelector('script'));assert(doc.querySelector('svg'));assert(doc.querySelector('pre').textContent.includes('Architecture'));});
 const doc=frame.contentDocument,win=frame.contentWindow;await delay(250);
 await check('Onboarding next, skip and finish',async()=>{let d=doc.querySelector('dialog');if(d){await click(doc,'Següent');assert(d.textContent.includes('02 / 07'));await click(doc,'Ometre');}await click(doc,'Aprendre');await click(doc,'Primers passos');for(let i=0;i<6;i++)await click(doc,'Següent');await click(doc,'Acabar');assert(!doc.querySelector('dialog'));await click(doc,'Editor');});
 await check('Create a new project',async()=>{win.confirm=()=>true;await click(doc,'Nou projecte');const d=doc.querySelector('dialog');input(d,'Nom').value='QA browser temporary';d.querySelector('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await delay(30);assert(doc.querySelectorAll('[data-node]').length===0);});
 await check('Add every node type',async()=>{for(const b of [...doc.querySelectorAll('.palette .node-button')]){b.click();await delay(5);} // rerenders invalidate old buttons but handlers remain valid
 assert(doc.querySelectorAll('[data-node]').length===18);});
 await check('Edit node and deterministic field',async()=>{edit(doc,'Nom','QA output');await delay(10);assert(doc.querySelector('[data-node].selected').textContent.includes('QA output'));});
 await check('Connect nodes and delete edge, undo/redo',async()=>{const docNodes=[...doc.querySelectorAll('[data-node]')];edit(doc,'Origen',docNodes[0].getAttribute('data-node'));edit(doc,'Destinació',docNodes[1].getAttribute('data-node'));edit(doc,'Etiqueta','PASS');await click(doc,'Connectar');assert(doc.querySelectorAll('[data-edge]').length===1);doc.querySelector('[data-edge] path[role=button]').dispatchEvent(new MouseEvent('click',{bubbles:true}));await delay(10);doc.querySelector('.inspector button.danger').click();await delay(10);assert(doc.querySelectorAll('[data-edge]').length===0);await click(doc,'Desfer');assert(doc.querySelectorAll('[data-edge]').length===1);await click(doc,'Refer');assert(doc.querySelectorAll('[data-edge]').length===0);});
 await check('Duplicate and delete selected node',async()=>{doc.querySelector('[data-node]').dispatchEvent(new MouseEvent('click',{bubbles:true}));await delay(10);await click(doc.querySelector('.inspector'),'Duplicar');assert(doc.querySelectorAll('[data-node]').length===19);await click(doc.querySelector('.inspector'),'Eliminar');assert(doc.querySelectorAll('[data-node]').length===18);});
 await check('Keyboard move, undo and redo',async()=>{doc.querySelector('[data-node]').dispatchEvent(new MouseEvent('click',{bubbles:true}));await delay(10);const before=doc.querySelector('[data-node].selected').getAttribute('transform');win.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));await delay(10);assert(doc.querySelector('[data-node].selected').getAttribute('transform')!==before);await click(doc,'Desfer');assert(doc.querySelector('[data-node].selected').getAttribute('transform')===before);await click(doc,'Refer');});
 await check('Save, reopen, duplicate and delete temporary project',async()=>{await click(doc,'Desar');await delay(80);assert(doc.querySelector('.project-title').textContent.includes('Desat localment'));await click(doc,'Projectes locals');await delay(60);assert(doc.querySelector('dialog').textContent.includes('QA browser temporary'));await click(doc.querySelector('dialog'),'Obrir');await delay(50);assert(doc.querySelectorAll('[data-node]').length===18);await click(doc.querySelector('.top-actions'),'Duplicar');const d=doc.querySelector('dialog');input(d,'Nom').value='QA copy temporary';d.querySelector('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await delay(100);await click(doc,'Projectes locals');await delay(60);assert(doc.querySelector('dialog').textContent.includes('QA copy temporary'));for(const r of [...doc.querySelectorAll('.project-row')])if(r.textContent.includes('QA '))r.querySelector('.danger').click();await delay(100);assert(!doc.querySelector('dialog').textContent.includes('QA browser temporary'));await click(doc,'Tancar');});
 await check('Language switching CA → ES → EN → CA',async()=>{for(const [code,text] of [['es','Analizar'],['en','Analyze'],['ca','Analitzar']]){const s=doc.querySelector('[aria-label="Idioma"],[aria-label="Language"]');s.value=code;s.dispatchEvent(new Event('change',{bubbles:true}));await delay(20);assert(button(doc,text));}});
 await check('Light, dark and system theme',async()=>{for(const theme of ['dark','light','system']){const s=doc.querySelector('select[aria-label="Tema"]');s.value=theme;s.dispatchEvent(new Event('change',{bubbles:true}));await delay(10);assert(['light','dark'].includes(doc.body.dataset.theme));if(theme!=='system')assert(doc.body.dataset.theme===theme);}});
 await check('Load template, analyzer, simulator and step/reset',async()=>{await click(doc,'Plantilles');await click(doc,'Obrir');await click(doc,'Analitzar');assert(doc.querySelectorAll('.metric').length>10);await click(doc,'Simular');await click(doc,'Pas següent');assert(doc.querySelectorAll('.trace li').length===1);await click(doc,'Executar simulació');assert(doc.querySelectorAll('.trace li').length===15);assert(doc.querySelector('main').textContent.includes('Simulació completada'));await click(doc,'Reiniciar');assert(doc.querySelectorAll('.trace li').length===0);});
 await check('Mobile 390px and tablet 768px: no page overflow',async()=>{for(const w of [390,768]){frame.style.width=w+'px';await delay(100);assert(doc.documentElement.scrollWidth<=w+2,'page overflow at '+w);await click(doc,'Editor');assert(doc.querySelector('.canvas-host').clientWidth<=w);await click(doc,'Analitzar');assert(doc.documentElement.scrollWidth<=w+2,'analysis overflow at '+w);}frame.style.width='1200px';});
 document.getElementById('summary').textContent=`${passed}/${total} browser tests passed`;document.getElementById('run').disabled=false;
}
document.getElementById('run').addEventListener('click',run);
